### ISSUE TITLE
Split Homework 2 into multiple files

### ISSUE THREAD

**Issue by Will-Sommers** [MyloTuT/IntroToPython#10]
Hey dude — it looks like HW2 is all in one file so common variable names like count aren't reused and what not as they are defined in other places. It might make it easier to split this into multiple files?

**Comment by MyloTuT** [comment]
Yea I’m working on clean up. I started a new organization structure but I need to clean up the old ones. Will do when I complete the current HW.

**Comment by MyloTuT** [comment]
I split these out. Closing issue.
