### ISSUE TITLE
Homework 2.2 

### ISSUE THREAD

**Issue by Will-Sommers** [MyloTuT/IntroToPython#9]
```
if user_int_request.isdigit() == True:
    print('Thanks for the integer')
else:
    print('that was NOT an integer:')
```

If I understand Python correctly, this `== True` is unnecessary. Take a look at the [is_digit](https://docs.python.org/3/library/stdtypes.html#str.isdigit) docs and you'll see that it already returns a `Boolean`. Any time you see yourself comparing something to be either `True` or `False`, you can just drop that comparison as they type is already a boolean.

**Comment by MyloTuT** [comment]
Commited changes for the boolean issue.
